---
name: Sistemas de numeración
locale: es
type: practice
beta: false
teacher_info: ''
language: text
id_format: "%05d"
order:
- 25
- 26
- 9
- 1
- 11
- 27
- 12
- 21
- 14
- 5
- 18
- 19
- 7
- 13
- 16
- 15
- 8
- 6
- 10
- 17
- 20
- 23
- 22
- 24
private: false
