---
name: Sistemas de numeración
locale: es
type: practice
beta: false
teacher_info: ''
language: text
id_format: "%05d"
order:
- 25
- 26
- 9
- 1
- 11
- 27
- 28
- 29
- 30
- 31
- 32
- 33
private: false
