---
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '10101'
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 5FB
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 3G99
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: SNES90
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '31091218'
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: CAFE
  checked: true
name: Letras en tus números
