---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '61'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '1600'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '7'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '16'
  checked: true
name: Ni 15 ni 17
