---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '2'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '3'
  checked: true
name: New exercise
