---
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: ":seven::five::two:"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: ":zero::zero::two::seven::five:"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: ":five::seven::two:"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: ":two::zero::zero: + :seven::zero: + :five:"
  checked: true
name: Decimal y ponderado
